import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Layout from "@/components/Layout";
import Image from "next/image";
import { Button } from "@web3uikit/core";
import Link from "next/link";

export default function Home() {
	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link href="./output.css" rel="stylesheet"></link>
			</Head>
			<Layout hideHeader={true}>
				<main className={styles.main}>
					<div className={styles.baseInfo}>
						<Image src="/images/asset-1-bc8cf690.webp" width={215} height={580} alt=''/>
						<div className={styles.info}>
								<h2 className={styles.title}>Get started with MetaMask Portfolio</h2>
								<p className={styles.desc}>Get a clear, comprehensive view of your accounts and wallets, across all networks. 
									Connect a MetaMask wallet or watch any Ethereum address.
								</p>
								<div className={styles.action}>
									<Link href="/points" className="text-xl font-bold">
										<Button text="Mint nft" type="button" theme="outline" size="large"/>
									</Link>
									<Button text="Connect Wallet" type="button" theme="moneyPrimary" size="large"/>
								</div>
						</div>
						<Image src="/images/asset-2-167109cd.webp" width={215} height={580} alt=''/>
					</div>
					<div className={styles.routeList}>
						<div className={styles.routeItem}>
							<Image src="/images/factory-46c54889.webp" width={215} height={580} alt=''/>
							<h2 className={styles.title}>Easily on-ramp or off-ramp</h2>
							<p className={styles.desc}>Convert cash to crypto or crypto for cash while maintaining control of your assets, no centralized exchange necessary.</p>
							<Button text="Connect Wallet" type="button" theme="moneyPrimary" size="large"/>
						</div>
						<div className={styles.routeItem}>
							<Image src="/images/factory-46c54889.webp" width={215} height={580} alt=''/>
							<h2 className={styles.title}>Easily on-ramp or off-ramp</h2>
							<p className={styles.desc}>Convert cash to crypto or crypto for cash while maintaining control of your assets, no centralized exchange necessary.</p>
							<Button text="Connect Wallet" type="button" theme="moneyPrimary" size="large"/>
						</div>
						<div className={styles.routeItem}>
							<Image src="/images/factory-46c54889.webp" width={215} height={580} alt=''/>
							<h2 className={styles.title}>Easily on-ramp or off-ramp</h2>
							<p className={styles.desc}>Convert cash to crypto or crypto for cash while maintaining control of your assets, no centralized exchange necessary.</p>
							<Button text="Connect Wallet" type="button" theme="moneyPrimary" size="large"/>
						</div>
					</div>
				</main>
			</Layout>
		</>
	);
}
